from .user import User
from .class_ import Class
from .student import Student
from .exam import Exam
from .attendance import Attendance
from .result import Result
from .fee import FeePayment
from .teacher import Teacher
from .subject import Subject
from .timetable import TimetableEntry
